### ISSUE TITLE
About Build error

### ISSUE THREAD

**Issue by anilnabin25** [iqonicdesignofficial/hope-ui-react-dashboard#1]
while trying to run the build command it always  shows error

![Screenshot from 2022-01-20 12-14-13](https://user-images.githubusercontent.com/53654225/150285538-dbd9d183-1cb4-4f9b-bb7e-cdb8b7c3eddd.png)

Could not understand the error

**Comment by chiragmistry007** [comment]
Hi,

The issue has been resolved
Please check the latest release
[(https://github.com/iqonicdesignofficial/hope-ui-react-dashboard/releases/tag/v1.1.2)](https://github.com/iqonicdesignofficial/hope-ui-react-dashboard/releases/tag/v1.1.2)

Thank you!
