### ISSUE TITLE
cannot run after npm install and npm start

### ISSUE THREAD

**Issue by gks0089** [iqonicdesignofficial/hope-ui-react-dashboard#3]
Total 8 errors found when start the project.

Module not found: Error: Can't resolve '../../../../store/setting/selectors' in 'D:\Learning Project\React\hope ui\hope-ui-react-dashboard\src\components\partials\dashboard\HeaderStyle'

ERROR in ./src/components/partials/dashboard/HeaderStyle/header.js 35:0-71
Module not found: Error: Can't resolve '../../../../store/setting/selectors' in 'D:\Learning Project\React\hope ui\hope-ui-react-dashboard\src\components\partials\dashboard\HeaderStyle'

ERROR in ./src/components/partials/dashboard/SidebarStyle/sidebar.js 13:0-71
Module not found: Error: Can't resolve '../../../../store/setting/selectors' in 'D:\Learning Project\React\hope ui\hope-ui-react-dashboard\src\components\partials\dashboard\SidebarStyle'

ERROR in ./src/components/setting/SettingOffCanvas.js 14:0-65
Module not found: Error: Can't resolve '../../store/setting/selectors' in 'D:\Learning Project\React\hope ui\hope-ui-react-dashboard\src\components\setting'

ERROR in ./src/layouts/dashboard/default.js 35:0-65
Module not found: Error: Can't resolve '../../store/setting/selectors' in 'D:\Learning Project\React\hope ui\hope-ui-react-dashboard\src\layouts\dashboard'

ERROR in ./src/store/setting/reducers.js 4:0-53
Module not found: Error: Can't resolve './state' in 'D:\Learning Project\React\hope ui\hope-ui-react-dashboard\src\store\setting'
Module not found: Error: Can't resolve '../../store/setting/selectors' in 'D:\Learning Project\React\hope ui\hope-ui-react-dashboard\src\views\dashboard'

ERROR in ./src/views/dashboard/special-pages/RtlSupport.js 42:0-68
Module not found: Error: Can't resolve '../../../store/setting/selectors' in 'D:\Learning Project\React\hope ui\hope-ui-react-dashboard\src\views\dashboard\special-pages'

ERROR in ./src/views/index.js 63:0-62
Module not found: Error: Can't resolve '../store/setting/selectors' in 'D:\Learning Project\React\hope ui\hope-ui-react-dashboard\src\views'

**Comment by TusharWatts** [comment]
Solved by including the tsconfig.json file and setting "allowJS" config option to be true

See: Add config file for setting typescript compiler configurations #4 

tsconfig.json
`
 {
    "compilerOptions": {
        "allowJs": true
    }
}
`
