### ISSUE TITLE
Blank page after creating build via create react app

### ISSUE THREAD

**Issue by TusharWatts** [iqonicdesignofficial/hope-ui-react-dashboard#5]
Trying to create build on both localhost and server via create react app (npm run build), however its showing blank page with no error. Nothing is rendered inside `<div id="root">`

> npm run build
> hope-ui-react@2.0.0 build 
> > react-scripts build
> 
> Creating an optimized production build...
> Compiled successfully.
> 
> File sizes after gzip:
> 
>   889.64 kB  build\static\js\main.e6edb506.js
>   96.26 kB   build\static\css\main.894dcfcd.css
>   1.68 kB    build\static\js\787.e170219d.chunk.js
> 
> The bundle size is significantly larger than recommended.
> Consider reducing it with code splitting: https://goo.gl/9VhYWB
> You can also analyze the project dependencies: https://goo.gl/LeUzfb
> 
> The project was built assuming it is hosted at ./.
> You can control this with the homepage field in your package.json.
> 
> The build folder is ready to be deployed.
> 
> Find out more about deployment here:
> 
>   https://cra.link/deployment
> 

I've added "homepage" attribute in package.json

`
"homepage": "."
`

I tried downgrading node js version, but in vain.

Hope-ui-react template version: 2.0.0
Node js version: 18.17.0

<img width="751" alt="image" src="https://github.com/iqonicdesignofficial/hope-ui-react-dashboard/assets/17049788/40a88720-9116-4251-8ed5-5d47e169b9c2">
<img width="616" alt="image" src="https://github.com/iqonicdesignofficial/hope-ui-react-dashboard/assets/17049788/77adbe69-8149-45c6-8d66-b1d4bcf8e91e">

**Comment by chiragmistry007** [comment]
Hi ,
Check your .env.production file  and update path to /

Example
PUBLIC_URL="/hope-ui/react/build"

to 

PUBLIC_URL="/"
